require('jobin.config.options')
require('jobin.config.mappings')
require('jobin.config.commands')
require('jobin.config.autocmds')
require('jobin.config.marks')
require('jobin.config.netrw')
-- require('jobin.config.find')
