-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#1a110f",
  base01 = "#140c0a",
  base02 = "#231917",
  base03 = "#53433f",
  base04 = "#d8c2bc",
  base05 = "#f1dfda",
  base06 = "#392e2b",
  base07 = "#423734",

  base08 = "#d3bb7a",
  base09 = "#d9c58d",
  base0A = "#e7bdb2",
  base0B = "#ffb5a1",
  base0C = "#534619",
  base0D = "#723524",
  base0E = "#5d4038",
  base0F = "#db9c8b",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#723524',
  fg = '#ffdbd1', -- normal text contrast
})

-- -- Fix completion menu selection visibility for native popup and blink.cmp
-- vim.api.nvim_set_hl(0, 'PmenuSel', {
--   bg = '#53433f',
--   bold = true
-- })

-- Make statusline transparent
vim.api.nvim_set_hl(0, 'StatusLine', { bg = 'none' })

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#c6a854',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a08c88',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d9c58d',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e7bdb2',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#8f4b39',
})
