-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#101510",
  base01 = "#0b0f0b",
  base02 = "#181d18",
  base03 = "#424940",
  base04 = "#c1c9be",
  base05 = "#e0e4db",
  base06 = "#2d322c",
  base07 = "#363a35",

  base08 = "#8fc5ce",
  base09 = "#a1ced6",
  base0A = "#b8ccb5",
  base0B = "#9dd49e",
  base0C = "#1f4d54",
  base0D = "#1e5127",
  base0E = "#3a4b3a",
  base0F = "#9bb797",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#1e5127',
  fg = '#b8f1b9', -- normal text contrast
})

-- Make statusline transparent
vim.api.nvim_set_hl(0, 'StatusLine', { bg = 'none' })

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#6cb2bf',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8c9389',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a1ced6',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b8ccb5',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#37693d',
})
